### ISSUE TITLE
How to target specific AWS resources and import via balcony

### ISSUE THREAD

**Issue by MOHD-MS** [oguzhan-yilmaz/balcony#49]
Hi,

Balcony is awesome illustration of boto3 use-case , Congratulations for the idea.

How we can create import.tf with respect to filtering tags,

I have 100 machines and 50machines only i need to import it to TF, so i am trying to filter via tags and list down those 50 machines and create the import.tf via balcony,

how. we can do this,

i just saw balcony terraform-wizard, but can you guide me,

with below example,

1. I have 100 s3 bucket and already 50 is under TF and it has terraform=true tag, i need to import rest of the 50 s3 buckets , how i can achieve that used balcony ? share the process !

any doubts let me know

**Comment by oguzhan-yilmaz** [comment]
Hey, thanks for reaching out! I hope you liked using balcony.
 
Unfortunately, balcony doesn't support filtering by tags. I think the best you can is:
- create terraform import blocks for all resources
- run 'terraform plan -generate-config-out' command to generate the actual Terraform code
- In the .tf files, you will have the Tags data, and you can manually delete the ones you don't want. (you may use vim and create a macro that would search for Tags > terraform=true and delete that resource)

I hope this is helpful.

**Comment by MOHD-MS** [comment]
Thank you for the response, Try to add this feature so it will be more useful scenario for TF import

**Comment by oguzhan-yilmaz** [comment]
Hey, @MOHD-MS, 

balcony v3.0.0 adds this feature now. I hope you like it.
